In [129]:
import pandas as pd

file_name = "X13_독거노인현황2.csv"

df_original = pd.read_csv(
    f"./{file_name}",
    encoding="utf-8-sig",
    engine="python",       # ✅ C 엔진 대신 Python 엔진 사용
    on_bad_lines="skip",   # 깨진 줄 무시
)

df = df_original.copy()
df.head(15)

    동별(1)  동별(2)        동별(3)    2020    2021    2022    2023    2024
0   동별(1)  동별(2)        동별(3)      합계      합계      합계      합계      합계
1   동별(1)  동별(2)        동별(3)       계       계       계       계       계
2   동별(1)  동별(2)        동별(3)       여       여       여       여       여
3   서울특별시     소계           소계  248176  263917  283884  298503  320592
4   서울특별시    종로구           소계    5895    5188    5402    6430    5373
5   서울특별시    종로구          사직동     395     330     342     359     344
6   서울특별시    종로구          삼청동     168     131     142     135     119
7   서울특별시    종로구          부암동     322     273     293     301     289
8   서울특별시    종로구          평창동     554     506     580     608     572
9   서울특별시    종로구          무악동     232     207     239     325     250
10  서울특별시    종로구          교남동     356     294     318     402     324
11  서울특별시    종로구          가회동     212     178     176     180     173
12  서울특별시    종로구  종로1.2.3.4가동     524     467     354     411     339
13  서울특별시    종로구      종로5.6가동     260     219     240     280     213
14  서울특별시    종로구          이화동     345     294     302     391     287

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   동별(1)   458 non-null    object
 1   동별(2)   458 non-null    object
 2   동별(3)   458 non-null    object
 3   2020    458 non-null    object
 4   2021    458 non-null    object
 5   2022    458 non-null    object
 6   2023    458 non-null    object
 7   2024    458 non-null    object
dtypes: object(8)
memory usage: 28.8+ KB

In [131]:
df.isnull().sum()

동별(1)    0
동별(2)    0
동별(3)    0
2020     0
2021     0
2022     0
2023     0
2024     0
dtype: int64

In [132]:
df.columns.tolist()

['동별(1)', '동별(2)', '동별(3)', '2020', '2021', '2022', '2023', '2024']

In [133]:
df = df.drop(index=[0, 1, 2]).reset_index(drop=True)
df

     동별(1) 동별(2) 동별(3)    2020    2021    2022    2023    2024
0    서울특별시    소계    소계  248176  263917  283884  298503  320592
1    서울특별시   종로구    소계    5895    5188    5402    6430    5373
2    서울특별시   종로구   사직동     395     330     342     359     344
3    서울특별시   종로구   삼청동     168     131     142     135     119
4    서울특별시   종로구   부암동     322     273     293     301     289
..     ...   ...   ...     ...     ...     ...     ...     ...
450  서울특별시   강동구  천호2동    1016    1036    1107    1168    1368
451  서울특별시   강동구    길동    1020    1123    1235    1361    1596
452  서울특별시   강동구   강일동       -     747     884     968    1103
453  서울특별시   강동구  상일1동       -     436     480     481     590
454  서울특별시   강동구  상일2동       -     285     318     337     373

[455 rows x 8 columns]

In [134]:
# 2. 컬럼명을 다시 한번 정리합니다.
df.columns = df.columns.str.strip()

# 3. '동별(1)' 컬럼을 삭제합니다.
#    '동별(1)'이 첫 번째 컬럼(인덱스 0)일 가능성이 높으므로,
#    이름 대신 인덱스를 사용하여 가장 안전하게 삭제합니다.
#    *만약 출력된 컬럼명에 '동별(1)'과 비슷한 이름이 있다면, 그 이름을 사용해야 합니다.*
#    **가장 확실한 방법: 첫 번째 컬럼을 삭제**
df = df.drop(df.columns[0], axis=1)

# 4. 남은 컬럼명 수정 ('동별(2)'와 '동별(3)'도 이름에 띄어쓰기 등이 남아있을 수 있으므로 strip() 후 수정)
df.rename(columns={'동별(2)': '지역구', '동별(3)': '동별'}, inplace=True)
df.head(50)

    지역구           동별    2020    2021    2022    2023    2024
0    소계           소계  248176  263917  283884  298503  320592
1   종로구           소계    5895    5188    5402    6430    5373
2   종로구          사직동     395     330     342     359     344
3   종로구          삼청동     168     131     142     135     119
4   종로구          부암동     322     273     293     301     289
5   종로구          평창동     554     506     580     608     572
6   종로구          무악동     232     207     239     325     250
7   종로구          교남동     356     294     318     402     324
8   종로구          가회동     212     178     176     180     173
9   종로구  종로1.2.3.4가동     524     467     354     411     339
10  종로구      종로5.6가동     260     219     240     280     213
11  종로구          이화동     345     294     302     391     287
12  종로구         창신1동     316     293     266     386     289
13  종로구         창신2동     393     377     415     571     428
14  종로구         창신3동     203     190     212     262     214
15  종로구         숭인1동     271     239     253     346     276
16  종로구         숭인2동     368     320     359     444     359
17  종로구        청운효자동     432     370     384     461     390
18  종로구          혜화동     544     500     527     568     507
19   중구           소계    4291    4525    4493    4750    4862
20   중구          소공동      35      34      36      42      43
21   중구          회현동     253     263     219     229     219
22   중구           명동     103     106      96     103     100
23   중구           필동     203     197     164     163     178
24   중구          장충동     151     160     157     162     170
25   중구          광희동     216     229     242     250     260
26   중구         을지로동      86      89      85      95      95
27   중구         신당5동     343     364     355     379     389
28   중구          황학동     354     382     390     424     461
29   중구          중림동     337     342     355     362     367
30   중구          신당동     288     308     314     345     362
31   중구          다산동     449     462     458     490     502
32   중구          약수동     719     784     800     858     876
33   중구          청구동     522     560     590     610     570
34   중구          동화동     232     245     232     238     270
35  용산구           소계    6911    7297    6501    6783    8341
36  용산구          후암동     609     651     596     628     848
37  용산구        용산2가동     407     420     379     396     551
38  용산구          남영동     314     310     262     276     399
39  용산구        원효로2동     379     378     381     399     812
40  용산구          효창동     208     231     210     218     363
41  용산구          용문동     332     373     362     397     595
42  용산구         이촌1동     639     659     555     589     247
43  용산구         이촌2동     299     339     315     323     485
44  용산구        이태원1동     281     291     247     259     539
45  용산구        이태원2동     356     373     319     374     664
46  용산구         서빙고동     356     369     312     328     423
47  용산구          보광동     583     618     566     552     433
48  용산구          청파동     598     627     605     653     592
49  용산구        원효로1동     326     343     312     330     497